### ISSUE TITLE
Add pending transactions

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#17]
PRD (https://github.com/Magickbase/ckb-explorer-public-issues/issues/130) has been confirmed by developers

**Comment by Kirl70** [comment]
Design Draft:
**Transaction page pending transactions** 
PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9669%3A31924&t=lGx8rPeS9XSaJiba-1
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/106060898/209820657-01e1233b-3b6f-4297-9ea9-02a046acf73b.png">
Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9669%3A32398&t=lGx8rPeS9XSaJiba-1
<img width="368" alt="image" src="https://user-images.githubusercontent.com/106060898/210956915-97b912da-cd6c-4d5c-8759-0bfc66ac2b93.png">

P.S. 
Since a new list has been added to the page, the transaction list also needs to be changed to a tab list style, as shown in the figure:
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/106060898/209822541-006fad8f-315d-4a83-bd22-502485023682.png">


**Account page**
PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9669%3A32557&t=lGx8rPeS9XSaJiba-1
<img width="882" alt="image" src="https://user-images.githubusercontent.com/106060898/209820902-033983d0-eeb8-420d-a122-af8a4fdcf82b.png">
Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9669%3A33686&t=lGx8rPeS9XSaJiba-1
<img width="387" alt="image" src="https://user-images.githubusercontent.com/106060898/209820997-d755d689-a2e2-4685-a927-40dd6328145d.png">

**Comment by Keith-CY** [comment]
@WhiteMinds @pygman please have a review

**Comment by WhiteMinds** [comment]
Take a brief look, there is no opinion
