### ISSUE TITLE
CKB explorer home page banner effect design

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#22]
1. Style effect:

https://user-images.githubusercontent.com/106060898/212798136-0247c91e-1bce-4f80-b050-0c7ef7442f4a.mp4

2. Ripple dynamic effect:

https://user-images.githubusercontent.com/106060898/212799748-74b4c0ff-94f7-4153-9706-da5ec4a0ed1e.mp4

Design ideas: use 2. the ripple dynamic effect to replace the irregular undulation effect inside the 1. style effect

**Comment by Keith-CY** [comment]
@Keith-CY add more description about the effect

**Comment by Keith-CY** [comment]
Two features were shown in 2 videos because they cannot be expressed together by UI design tools.

The idea comes from [Movable Type Printing](https://en.wikipedia.org/wiki/Movable_type), heartbeat, and water ripple.

1. The surface consists of many cuboids;
2. Text `CKB` protrudes from the surface;
3. Once a block is minted, the `CKB` pulse and leads to a ripple effect;
4. After the ripple, `x` cuboids keep protruding, `x` is the count of tx in the minted block.

It is similar to https://echarts.apache.org/examples/en/editor.html?c=bar3d-voxelize-image&gl=1 visually

<img width="915" alt="image" src="https://user-images.githubusercontent.com/7271329/215253164-2b91b54e-3567-43fa-9513-406fade3b16a.png">

Furthermore, the text `CKB` should be configurable to deliver more info, e.g. a countdown of an activity.

Is the description clear enough for development? @WhiteMinds

**Comment by WhiteMinds** [comment]
@Keith-CY Probably understand, the technical problems need to wait for the start of the task after the research and then discuss.
